// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duhbawuidpknylxuqjti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aGJhd3VpZHBrbnlseHVxanRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzgzOTksImV4cCI6MjA3MTAxNDM5OX0.qWSVHl3mLUuaJ_wj8_8202olmHKB8nowJUhz3F5GLW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});